USE wedeal;
GO
IF OBJECT_ID(N'dbo.posts') IS NOT NULL
BEGIN
	DROP TABLE wedeal.dbo.posts;
END
GO
CREATE TABLE dbo.posts
(
	id INT NOT NULL IDENTITY(1,1),
	title VARCHAR(50) NOT NULL DEFAULT '',
	publication_date DATETIME NOT NULL DEFAULT GETDATE(),
	content VARCHAR(MAX) NOT NULL DEFAULT '',
	status BIT NOT NULL DEFAULT 1,
	id_user INT NOT NULL,
	CONSTRAINT PK_POSTS_ID PRIMARY KEY(id),
	CONSTRAINT FK_POSTS_ID_USER FOREIGN KEY(id_user) REFERENCES wedeal.dbo.users(id),
);
GO
