USE wedeal;
GO
IF OBJECT_ID(N'dbo.[auths]') IS NOT NULL
BEGIN
	DROP TABLE wedeal.dbo.[auths];
END
GO
CREATE TABLE dbo.[auths]
(
	id INT NOT NULL IDENTITY(1,1),
	id_user INT NOT NULL,
	[username] VARCHAR(20) NOT NULL UNIQUE,
	[password] VARCHAR(64) NOT NULL DEFAULT 'E7568F431A357EC0FD4DC7734C54D4EE179F1EBFC387F7F68A6A7E15052A7572',
	CONSTRAINT PK_AUTHS_ID PRIMARY KEY(id),
	CONSTRAINT FK_AUTHS_ID_USER FOREIGN KEY(id_user) REFERENCES wedeal.dbo.users(id),
);
GO
