INSERT INTO dbo.countries (name) VALUES ('Australia');
INSERT INTO dbo.countries (name) VALUES ('Austria');
INSERT INTO dbo.countries (name) VALUES ('Azerbaiyán');
INSERT INTO dbo.countries (name) VALUES ('Anguilla');
INSERT INTO dbo.countries (name) VALUES ('Argentina');
INSERT INTO dbo.countries (name) VALUES ('Armenia');
INSERT INTO dbo.countries (name) VALUES ('Bielorrusia');
INSERT INTO dbo.countries (name) VALUES ('Belice');
INSERT INTO dbo.countries (name) VALUES ('Bélgica');
INSERT INTO dbo.countries (name) VALUES ('Bermudas');
INSERT INTO dbo.countries (name) VALUES ('Bulgaria');
INSERT INTO dbo.countries (name) VALUES ('Brasil');
INSERT INTO dbo.countries (name) VALUES ('Reino Unido');
INSERT INTO dbo.countries (name) VALUES ('Hungría');
INSERT INTO dbo.countries (name) VALUES ('Vietnam');
INSERT INTO dbo.countries (name) VALUES ('Haiti');
INSERT INTO dbo.countries (name) VALUES ('Guadalupe');
INSERT INTO dbo.countries (name) VALUES ('Alemania');
INSERT INTO dbo.countries (name) VALUES ('Países Bajos, Holanda');
INSERT INTO dbo.countries (name) VALUES ('Grecia');
INSERT INTO dbo.countries (name) VALUES ('Georgia');
INSERT INTO dbo.countries (name) VALUES ('Dinamarca');
INSERT INTO dbo.countries (name) VALUES ('Egipto');
INSERT INTO dbo.countries (name) VALUES ('Israel');
INSERT INTO dbo.countries (name) VALUES ('India');
INSERT INTO dbo.countries (name) VALUES ('Irán');
INSERT INTO dbo.countries (name) VALUES ('Irlanda');
INSERT INTO dbo.countries (name) VALUES ('España');
INSERT INTO dbo.countries (name) VALUES ('Italia');
INSERT INTO dbo.countries (name) VALUES ('Kazajstán');
INSERT INTO dbo.countries (name) VALUES ('Camerún');
INSERT INTO dbo.countries (name) VALUES ('Canadá');
INSERT INTO dbo.countries (name) VALUES ('Chipre');
INSERT INTO dbo.countries (name) VALUES ('Kirguistán');
INSERT INTO dbo.countries (name) VALUES ('China');
INSERT INTO dbo.countries (name) VALUES ('Costa Rica');
INSERT INTO dbo.countries (name) VALUES ('Kuwait');
INSERT INTO dbo.countries (name) VALUES ('Letonia');
INSERT INTO dbo.countries (name) VALUES ('Libia');
INSERT INTO dbo.countries (name) VALUES ('Lituania');
INSERT INTO dbo.countries (name) VALUES ('Luxemburgo');
INSERT INTO dbo.countries (name) VALUES ('México');
INSERT INTO dbo.countries (name) VALUES ('Moldavia');
INSERT INTO dbo.countries (name) VALUES ('Mónaco');
INSERT INTO dbo.countries (name) VALUES ('Nueva Zelanda');
INSERT INTO dbo.countries (name) VALUES ('Noruega');
INSERT INTO dbo.countries (name) VALUES ('Polonia');
INSERT INTO dbo.countries (name) VALUES ('Portugal');
INSERT INTO dbo.countries (name) VALUES ('Reunión');
INSERT INTO dbo.countries (name) VALUES ('Rusia');
INSERT INTO dbo.countries (name) VALUES ('El Salvador');
INSERT INTO dbo.countries (name) VALUES ('Eslovaquia');
INSERT INTO dbo.countries (name) VALUES ('Eslovenia');
INSERT INTO dbo.countries (name) VALUES ('Surinam');
INSERT INTO dbo.countries (name) VALUES ('Estados Unidos');
INSERT INTO dbo.countries (name) VALUES ('Tadjikistan');
INSERT INTO dbo.countries (name) VALUES ('Turkmenistan');
INSERT INTO dbo.countries (name) VALUES ('Islas Turcas y Caicos');
INSERT INTO dbo.countries (name) VALUES ('Turquía');
INSERT INTO dbo.countries (name) VALUES ('Uganda');
INSERT INTO dbo.countries (name) VALUES ('Uzbekistán');
INSERT INTO dbo.countries (name) VALUES ('Ucrania');
INSERT INTO dbo.countries (name) VALUES ('Finlandia');
INSERT INTO dbo.countries (name) VALUES ('Francia');
INSERT INTO dbo.countries (name) VALUES ('República Checa');
INSERT INTO dbo.countries (name) VALUES ('Suiza');
INSERT INTO dbo.countries (name) VALUES ('Suecia');
INSERT INTO dbo.countries (name) VALUES ('Estonia');
INSERT INTO dbo.countries (name) VALUES ('Corea del Sur');
INSERT INTO dbo.countries (name) VALUES ('Japón');
INSERT INTO dbo.countries (name) VALUES ('Croacia');
INSERT INTO dbo.countries (name) VALUES ('Rumanía');
INSERT INTO dbo.countries (name) VALUES ('Hong Kong');
INSERT INTO dbo.countries (name) VALUES ('Indonesia');
INSERT INTO dbo.countries (name) VALUES ('Jordania');
INSERT INTO dbo.countries (name) VALUES ('Malasia');
INSERT INTO dbo.countries (name) VALUES ('Singapur');
INSERT INTO dbo.countries (name) VALUES ('Taiwan');
INSERT INTO dbo.countries (name) VALUES ('Bosnia y Herzegovina');
INSERT INTO dbo.countries (name) VALUES ('Bahamas');
INSERT INTO dbo.countries (name) VALUES ('Chile');
INSERT INTO dbo.countries (name) VALUES ('Colombia');
INSERT INTO dbo.countries (name) VALUES ('Islandia');
INSERT INTO dbo.countries (name) VALUES ('Corea del Norte');
INSERT INTO dbo.countries (name) VALUES ('Macedonia');
INSERT INTO dbo.countries (name) VALUES ('Malta');
INSERT INTO dbo.countries (name) VALUES ('Pakistán');
INSERT INTO dbo.countries (name) VALUES ('Papúa-Nueva Guinea');
INSERT INTO dbo.countries (name) VALUES ('Perú');
INSERT INTO dbo.countries (name) VALUES ('Filipinas');
INSERT INTO dbo.countries (name) VALUES ('Arabia Saudita');
INSERT INTO dbo.countries (name) VALUES ('Tailandia');
INSERT INTO dbo.countries (name) VALUES ('Emiratos árabes Unidos');
INSERT INTO dbo.countries (name) VALUES ('Groenlandia');
INSERT INTO dbo.countries (name) VALUES ('Venezuela');
INSERT INTO dbo.countries (name) VALUES ('Zimbabwe');
INSERT INTO dbo.countries (name) VALUES ('Kenia');
INSERT INTO dbo.countries (name) VALUES ('Algeria');
INSERT INTO dbo.countries (name) VALUES ('Líbano');
INSERT INTO dbo.countries (name) VALUES ('Botsuana');
INSERT INTO dbo.countries (name) VALUES ('Tanzania');
INSERT INTO dbo.countries (name) VALUES ('Namibia');
INSERT INTO dbo.countries (name) VALUES ('Ecuador');
INSERT INTO dbo.countries (name) VALUES ('Marruecos');
INSERT INTO dbo.countries (name) VALUES ('Ghana');
INSERT INTO dbo.countries (name) VALUES ('Siria');
INSERT INTO dbo.countries (name) VALUES ('Nepal');
INSERT INTO dbo.countries (name) VALUES ('Mauritania');
INSERT INTO dbo.countries (name) VALUES ('Seychelles');
INSERT INTO dbo.countries (name) VALUES ('Paraguay');
INSERT INTO dbo.countries (name) VALUES ('Uruguay');
INSERT INTO dbo.countries (name) VALUES ('Congo (Brazzaville)');
INSERT INTO dbo.countries (name) VALUES ('Cuba');
INSERT INTO dbo.countries (name) VALUES ('Albania');
INSERT INTO dbo.countries (name) VALUES ('Nigeria');
INSERT INTO dbo.countries (name) VALUES ('Zambia');
INSERT INTO dbo.countries (name) VALUES ('Mozambique');
INSERT INTO dbo.countries (name) VALUES ('Angola');
INSERT INTO dbo.countries (name) VALUES ('Sri Lanka');
INSERT INTO dbo.countries (name) VALUES ('Etiopía');
INSERT INTO dbo.countries (name) VALUES ('Túnez');
INSERT INTO dbo.countries (name) VALUES ('Bolivia');
INSERT INTO dbo.countries (name) VALUES ('Panamá');
INSERT INTO dbo.countries (name) VALUES ('Malawi');
INSERT INTO dbo.countries (name) VALUES ('Liechtenstein');
INSERT INTO dbo.countries (name) VALUES ('Bahrein');
INSERT INTO dbo.countries (name) VALUES ('Barbados');
INSERT INTO dbo.countries (name) VALUES ('Chad');
INSERT INTO dbo.countries (name) VALUES ('Man, Isla de');
INSERT INTO dbo.countries (name) VALUES ('Jamaica');
INSERT INTO dbo.countries (name) VALUES ('Malí');
INSERT INTO dbo.countries (name) VALUES ('Madagascar');
INSERT INTO dbo.countries (name) VALUES ('Senegal');
INSERT INTO dbo.countries (name) VALUES ('Togo');
INSERT INTO dbo.countries (name) VALUES ('Honduras');
INSERT INTO dbo.countries (name) VALUES ('República Dominicana');
INSERT INTO dbo.countries (name) VALUES ('Mongolia');
INSERT INTO dbo.countries (name) VALUES ('Irak');
INSERT INTO dbo.countries (name) VALUES ('Sudáfrica');
INSERT INTO dbo.countries (name) VALUES ('Aruba');
INSERT INTO dbo.countries (name) VALUES ('Gibraltar');
INSERT INTO dbo.countries (name) VALUES ('Afganistán');
INSERT INTO dbo.countries (name) VALUES ('Andorra');
INSERT INTO dbo.countries (name) VALUES ('Antigua y Barbuda');
INSERT INTO dbo.countries (name) VALUES ('Bangladesh');
INSERT INTO dbo.countries (name) VALUES ('Benín');
INSERT INTO dbo.countries (name) VALUES ('Bután');
INSERT INTO dbo.countries (name) VALUES ('Islas Virgenes Británicas');
INSERT INTO dbo.countries (name) VALUES ('Brunéi');
INSERT INTO dbo.countries (name) VALUES ('Burkina Faso');
INSERT INTO dbo.countries (name) VALUES ('Burundi');
INSERT INTO dbo.countries (name) VALUES ('Camboya');
INSERT INTO dbo.countries (name) VALUES ('Cabo Verde');
INSERT INTO dbo.countries (name) VALUES ('Comores');
INSERT INTO dbo.countries (name) VALUES ('Congo (Kinshasa)');
INSERT INTO dbo.countries (name) VALUES ('Cook, Islas');
INSERT INTO dbo.countries (name) VALUES ('Costa de Marfil');
INSERT INTO dbo.countries (name) VALUES ('Djibouti, Yibuti');
INSERT INTO dbo.countries (name) VALUES ('Timor Oriental');
INSERT INTO dbo.countries (name) VALUES ('Guinea Ecuatorial');
INSERT INTO dbo.countries (name) VALUES ('Eritrea');
INSERT INTO dbo.countries (name) VALUES ('Feroe, Islas');
INSERT INTO dbo.countries (name) VALUES ('Fiyi');
INSERT INTO dbo.countries (name) VALUES ('Polinesia Francesa');
INSERT INTO dbo.countries (name) VALUES ('Gabón');
INSERT INTO dbo.countries (name) VALUES ('Gambia');
INSERT INTO dbo.countries (name) VALUES ('Granada');
INSERT INTO dbo.countries (name) VALUES ('Guatemala');
INSERT INTO dbo.countries (name) VALUES ('Guernsey');
INSERT INTO dbo.countries (name) VALUES ('Guinea');
INSERT INTO dbo.countries (name) VALUES ('Guinea-Bissau');
INSERT INTO dbo.countries (name) VALUES ('Guyana');
INSERT INTO dbo.countries (name) VALUES ('Jersey');
INSERT INTO dbo.countries (name) VALUES ('Kiribati');
INSERT INTO dbo.countries (name) VALUES ('Laos');
INSERT INTO dbo.countries (name) VALUES ('Lesotho');
INSERT INTO dbo.countries (name) VALUES ('Liberia');
INSERT INTO dbo.countries (name) VALUES ('Maldivas');
INSERT INTO dbo.countries (name) VALUES ('Martinica');
INSERT INTO dbo.countries (name) VALUES ('Mauricio');
INSERT INTO dbo.countries (name) VALUES ('Myanmar');
INSERT INTO dbo.countries (name) VALUES ('Nauru');
INSERT INTO dbo.countries (name) VALUES ('Antillas Holandesas');
INSERT INTO dbo.countries (name) VALUES ('Nueva Caledonia');
INSERT INTO dbo.countries (name) VALUES ('Nicaragua');
INSERT INTO dbo.countries (name) VALUES ('Níger');
INSERT INTO dbo.countries (name) VALUES ('Norfolk Island');
INSERT INTO dbo.countries (name) VALUES ('Omán');
INSERT INTO dbo.countries (name) VALUES ('Isla Pitcairn');
INSERT INTO dbo.countries (name) VALUES ('Qatar');
INSERT INTO dbo.countries (name) VALUES ('Ruanda');
INSERT INTO dbo.countries (name) VALUES ('Santa Elena');
INSERT INTO dbo.countries (name) VALUES ('San Cristobal y Nevis');
INSERT INTO dbo.countries (name) VALUES ('Santa Lucía');
INSERT INTO dbo.countries (name) VALUES ('San Pedro y Miquelón');
INSERT INTO dbo.countries (name) VALUES ('San Vincente y Granadinas');
INSERT INTO dbo.countries (name) VALUES ('Samoa');
INSERT INTO dbo.countries (name) VALUES ('San Marino');
INSERT INTO dbo.countries (name) VALUES ('San Tomé y Príncipe');
INSERT INTO dbo.countries (name) VALUES ('Serbia y Montenegro');
INSERT INTO dbo.countries (name) VALUES ('Sierra Leona');
INSERT INTO dbo.countries (name) VALUES ('Islas Salomón');
INSERT INTO dbo.countries (name) VALUES ('Somalia');
INSERT INTO dbo.countries (name) VALUES ('Sudán');
INSERT INTO dbo.countries (name) VALUES ('Swazilandia');
INSERT INTO dbo.countries (name) VALUES ('Tokelau');
INSERT INTO dbo.countries (name) VALUES ('Tonga');
INSERT INTO dbo.countries (name) VALUES ('Trinidad y Tobago');
INSERT INTO dbo.countries (name) VALUES ('Tuvalu');
INSERT INTO dbo.countries (name) VALUES ('Vanuatu');
INSERT INTO dbo.countries (name) VALUES ('Wallis y Futuna');
INSERT INTO dbo.countries (name) VALUES ('Sáhara Occidental');
INSERT INTO dbo.countries (name) VALUES ('Yemen');
INSERT INTO dbo.countries (name) VALUES ('Puerto Rico');
