INSERT INTO dbo.work_areas (title) VALUES ('HR');
INSERT INTO dbo.work_areas (title) VALUES ('Designing');
INSERT INTO dbo.work_areas (title) VALUES ('Managment');
INSERT INTO dbo.work_areas (title) VALUES ('Information Technology');
INSERT INTO dbo.work_areas (title) VALUES ('Education');
INSERT INTO dbo.work_areas (title) VALUES ('Advocate');
INSERT INTO dbo.work_areas (title) VALUES ('Business Development');
INSERT INTO dbo.work_areas (title) VALUES ('Health & Fitness');
INSERT INTO dbo.work_areas (title) VALUES ('Agricultural');
INSERT INTO dbo.work_areas (title) VALUES ('BPO');
INSERT INTO dbo.work_areas (title) VALUES ('Sales');
INSERT INTO dbo.work_areas (title) VALUES ('Consultant');
INSERT INTO dbo.work_areas (title) VALUES ('Digital Media');
INSERT INTO dbo.work_areas (title) VALUES ('Building & Construction');
INSERT INTO dbo.work_areas (title) VALUES ('Automobile');
INSERT INTO dbo.work_areas (title) VALUES ('Banking');
INSERT INTO dbo.work_areas (title) VALUES ('Engineering');
INSERT INTO dbo.work_areas (title) VALUES ('Food & Beverages');
INSERT INTO dbo.work_areas (title) VALUES ('Finance');
INSERT INTO dbo.work_areas (title) VALUES ('Apparel');
INSERT INTO dbo.work_areas (title) VALUES ('Accountant');
INSERT INTO dbo.work_areas (title) VALUES ('Architects');
INSERT INTO dbo.work_areas (title) VALUES ('Public Relations');
INSERT INTO dbo.work_areas (title) VALUES ('Arts');
INSERT INTO dbo.work_areas (title) VALUES ('Aviation');
INSERT INTO dbo.work_areas (title) VALUES ('Others');